spring:
  application:
    name: identity-service
server:
  port: 8001
  servlet:
    context-path: /identity

com:
  example:
    firebase:
      web-api-key: AIzaSyDsRZMGfdM_zZEUmaaBG1E2BqlIAOem5rM
      private-key: private-key.json

springdoc:
  swagger-ui:
    use-root-path: true
    enabled: true