version: '3.9'

services:
  api-gateway:
    image: doublecreamcheze/intellab_ops:api-gateway-latest
    ports:
      - "8100:8000"

  identity-service:
    image: doublecreamcheze/intellab_ops:identity-service-latest
    ports:
      - "8101:8001"

  course-service:
    image: doublecreamcheze/intellab_ops:course-service-latest
    ports:
      - "8102:8002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/intellab-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - db

  problem-service:
    image: doublecreamcheze/intellab_ops:problem-service-latest
    ports:
      - "8103:8003"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/intellab-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intellab-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: intellab-db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
