server:
  port: 8000
app:
  api-prefix: /api
spring:
  application:
      name: api-gateway
  cloud:
    gateway:
#      public-paths:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
#              - "http://${DOCKER_HOST_NAME}:${DOCKER_API_GATEWAY_PORT}"
#              - "http://${DOCKER_HOST_NAME}:${DOCKER_IDENTITY_PORT}"
#              - "http://${DOCKER_HOST_NAME}:${DOCKER_COURSE_PORT}"
              - "http://localhost:3000"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: identity-service
          uri: http://${HOST_NAME}:${IDENTITY_PORT}
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=1
        - id: course-service
          uri: http://${HOST_NAME}:${COURSE_PORT}
          predicates:
            - Path=${app.api-prefix}/course/**
          filters:
            - StripPrefix=1