spring:
  application:
    name: course-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
#        generate_statistics: true
    #show-sql: true
server:
  port: 8002
  servlet:
    context-path: /course

#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: mysslkey

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
# Swagger

springdoc:
  swagger-ui:
    use-root-path: true
    enabled: true

cloudinary:
  url: ${CLOUDINARY_URL}
