services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8101:8001"
    networks:
      - backend-network
    container_name: identity-service
networks:
  backend-network:
    driver: bridge

#service:
#  app:
#    build:
#      context: .
#      platforms:
#        - linux/amd64
#        - linux/arm64
#    ports:
#      - "8101:8001"
#    container_name: identity-service
