spring:
  application:
    name: payment-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /payment
  port: 8005
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: mysslkey

springdoc:
  swagger-ui:
    use-root-path: true
    enabled: true

vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET_KEY}
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html  # Use production URL in live mode
  return-url: https://${HOST_NAME}:${PAYMENT_PORT}/payment/vnpay/vnpay-return
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
