apiVersion: v1
kind: Service
metadata:
  name: prometheus-adapter
spec:
  selector:
    app: prometheus-adapter
  ports:
    - port: 443
      targetPort: 6443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-adapter
  template:
    metadata:
      labels:
        app: prometheus-adapter
    spec:
      containers:
        - name: prometheus-adapter
          image: directxman12/k8s-prometheus-adapter-amd64:v0.8.3
          ports:
            - containerPort: 6443
          volumeMounts:
            - name: config-volume
              mountPath: /etc/adapter/
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-adapter-config