apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 2358
      targetPort: 2358
      nodePort: 32358  # Exposes on 32358 for external access
  type: NodePort  # Change LoadBalancer to NodePort for local Kubernetes

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      restartPolicy: Always  # Ensures it restarts if it crashes
      containers:
        - name: server-container
          image: judge0/judge0:1.13.0
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: judge0-config
          env:
            - name: DATABASE_URL
              value: "postgresql://judge0:htht01225923050@db:5432/judge0"
          resources:
            limits:
              memory: "256Mi"
              cpu: "1000m"
          ports:
            - containerPort: 2358
              protocol: TCP
