apiVersion: v1
kind: Service
metadata:
  name: workers
spec:
  selector:
    app: workers
  ports:
    - port: 2358
      targetPort: 2358
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workers
  template:
    metadata:
      labels:
        app: workers
    spec:
      containers:
        - name: workers-container
          image: judge0/judge0:1.13.0
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: judge0-config
          command:
            - "/bin/sh"
            - "-c"
            - "./scripts/workers"
          volumeMounts:
            - name: judge0-config-volume
              mountPath: /judge0.conf
              subPath: judge0.conf
              readOnly: true
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 2358
      volumes:
        - name: judge0-config-volume
          configMap:
            name: judge0-config
