apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: workers-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workers
  minReplicas: 1
  maxReplicas: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
          
    - type: Pods
      pods:
        metric:
          name: redis_queue_length
        target:
          type: AverageValue
          averageValue: 10