services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8102:8002" # Match the exposed port in the Dockerfile
    container_name: course-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/course-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: htht01225923050
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: htht01225923050
      POSTGRES_DB: course-service
    ports:
      - "5433:5432"