spring:
  application:
    name: problem-service
  datasource:
    url: ${DB_URL} #5433 jdbc:postgresql://localhost:5432/course-service #
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD} #htht01225923050
    driver-class-name: org.postgresql.Driver
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          json_format_mapper: com.example.problemservice.mapper.JacksonJsonFormatMapperCustom #CustomJacksonJsonFormatMapper
            #descriptor:
               # sql:
               # use:
                   # sql-comments: true
#        generate_statistics: true
#        format_sql: true
#        use_sql_comments: true

server:
  servlet:
    context-path: /problem
  port: 8003

judge0:
  api:
    url: ${JUDGE0_URL} #http://localhost:2358 #
    callback_url: "http://host.minikube.internal:${PROBLEM_PORT}/problem/problem-submissions/update/submission/callback"
    run_code_callback_url: "http://host.minikube.internal:${PROBLEM_PORT}/problem/problem-run-code/update/run-code/callback"
#    callback_url: "http://host.docker.internal:${PROBLEM_PORT}/problem/problem-submissions/update/submission/callback"
#    run_code_callback_url: "http://host.docker.internal:${PROBLEM_PORT}/problem/problem-run-code/update/run-code/callback"
    custom_checker_callback_url_to_get_actual_output: "http://host.docker.internal:${PROBLEM_PORT}/problem/problem-submissions/custom-checker/update/submission/callback"
    custom_checker_run_code_callback_url_to_get_actual_output: "http://host.docker.internal:${PROBLEM_PORT}/problem/problem-run-code/custom-checker/update/run-code/callback-to-get-actual-output"
    custom_checker_run_code_callback_url_to_get_checking_result: "http://host.docker.internal:${PROBLEM_PORT}/problem/problem-run-code/custom-checker/update/run-code/callback-to-checking-result"

k8s:
  server:
    url: ${K8S_SERVER_URL}
    token: ${K8S_TOKEN}

#logging:
#  level:
#    root: TRACE
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
#

springdoc:
  swagger-ui:
    use-root-path: true
    enabled: true

mount_path: ${MOUNT_PATH}