name: Build and push spring app Docker image to docker hub

on:
  push:
    branches:
      - main
      - develop
      - feature
      - deploy
      - test-deploy

  pull_request:
    branches:
      - main
      - develop
      - feature
      - deploy
      - test-deploy

    paths:
      - 'api-gateway/**'
      - 'course-service/**'
      - 'identity-service/**'
      - 'problem-service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        service: [api-gateway, course-service, identity-service, problem-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          cd ${{ matrix.service }}
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.service }}:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.service }}:latest