name: Build and push spring app Docker image to docker hub

on:
  push:
    branches:
      - main
      - develop
      - feature
      - deploy
      - test-deploy

    paths:
    - 'api-gateway/**'
    - 'course-service/**'
    - 'identity-service/**'
    - 'problem-service/**'

  pull_request:
    branches:
      - main
      - develop
      - feature
      - deploy
      - test-deploy

    paths:
      - 'api-gateway/**'
      - 'course-service/**'
      - 'identity-service/**'
      - 'problem-service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Cheapest GitHub-hosted runner

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ENVIRONMENT_FILE: ${{ secrets.ENVIRONMENT_FILE }}
      FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

    strategy:
      matrix:
        service: [api-gateway, course-service, identity-service, problem-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_USERNAME }}" | docker login -u "${{ secrets.DOCKER_HUB_PASSWORD }}" --password-stdin

      # - name: Set up environment
      #   uses: docker/buildx-action@v2
      #   with:
      #     driver-opts: name=intellab-env

      # - name: create .env file
      #   #Hard value environment variable
      #   run: echo "HOST_NAME=host.docker.internal" >> .env

      - name: Create .env file from secret (Multiline Support)
        run: printf "%s" "${{ secrets.ENVIRONMENT_FILE }}" > .env

      # Optional:
      - name: Verify .env file
        run: cat .env

      - name: create credentials file
        run: |
          echo "${{ secrets.FIREBASE_CONFIG }}" > identity-service/src/main/resources/firebase-config.json
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > identity-service/src/main/resources/google-credentials.json
          echo "${{ secrets.PRIVATE_KEY }}" > identity-service/src/main/resources/private-key.json
          echo "${{ secrets.FIREBASE_CONFIG }}" > course-service/src/main/resources/firebase-config.json

      - name: Copy .env file to service folder
        run: cp .env ${{ matrix.service }}/.env

      - name: Set up environment
        uses: docker buildx create --name intellab-env --use

      - name: Build and push Docker image
        run: |
          cd ${{ matrix.service }}
          docker buildx build --platform linux/amd64,linux/arm64 -t doublecreamcheze/intellab_ops:${{ matrix.service }}-latest --push .