name: Update Secret
on: workflow_dispatch  # Allows manual trigger

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  update-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Update Repository Secret
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.CICD_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/doublecreamchezeee/intellab_be/actions/secrets/YOUR_SECRET_NAME \
            -d '{"encrypted_value": "<new_secret_value>"}'
